# Generated by Django 2.2.12 on 2020-11-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='smisforms',
            new_name='smisformsdb',
        ),
    ]
